version: '3'
services:
  postgres:
    image: postgres:15
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command: ["start-dev"]
    network_mode: "host"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    depends_on:
      - postgres
  
  api:
    container_name: api
    image: rcbj/api
    environment:
      - CONFIG_FILE=./env/local.js
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        CONFIG_FILE: ${CONFIG_FILE}
    network_mode: "host"
    depends_on:
      - keycloak
  
  client:
    container_name: client
    image: rcbj/client
    environment:
      - CONFIG_FILE=./env/local.js
    build:
      context: .
      dockerfile: client/Dockerfile 
      args:
        CONFIG_FILE: ${CONFIG_FILE}
    network_mode: "host"
    depends_on:
      - api

volumes:
  postgres_data:
