version: '3'
services:
  api:
    container_name: api
    image: rcbj/api
    environment:
      - CONFIG_FILE=./env/local.js
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        CONFIG_FILE: ${CONFIG_FILE}
    ports:
      - "4000:4000"
  client:
    container_name: client
    image: rcbj/client
    environment:
      - CONFIG_FILE=./env/local.js
    build:
      context: .
      dockerfile: ./client/Dockerfile 
      args:
        CONFIG_FILE: ${CONFIG_FILE}
    ports:
      - "3000:3000"
